name: publish release version

on:
  push:
    tags:
      - "latest"   # 你当前就是推送名为 latest 的 tag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 读取 package.json 的 packageManager 安装 pnpm（不再在 action-setup 里指定 version）
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build+zip

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build

      # 如果 tag=latest 的 release 已存在，则更新；否则创建
      - name: Create or Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}                          # "latest"
          name: "${{ github.ref_name }}"               # Release 名称
          draft: false
          prerelease: false
          allowUpdates: true                                   # 允许更新已存在的 release
          replacesArtifacts: true                              # 替换同名资产
          artifactErrorsFailBuild: true
          artifacts: |
            build/chrome.zip,
            build/edge.zip,
            build/firefox.zip,
            build/userscript.zip,
            build/thunderbird.zip
          # 也可以用通配符：artifacts: "build/*.zip"
